### ISSUE TITLE
Compiler Error with Trunk fpc

### ISSUE THREAD

**Issue by maxm74** [bgrabitmap/bgrabitmap#281]
bgraunits.pas(126,36) Error: Identifier not found "TResolutionUnit"

After this Committ ([#278](https://github.com/bgrabitmap/bgrabitmap/pull/278)

**Comment by maxm74** [comment]
I tried to pull the solution but it doesn't let me write.
did you block me?

**Comment by maxm74** [comment]
in any case this solves the problem and i've added a function to convert Sizes from/to cm/inch.

I changed my project to use Resample in Pixel, but I think the function to convert physical dimensions (now PhysicalSizeConvert) is necessary, then you decide...

[bgraunits.zip](https://github.com/user-attachments/files/20285046/bgraunits.zip)

**Comment by circular17** [comment]
Hi @maxm74,

Thanks a lot for jumping in so quickly to fix compilation.

Just to clarify: you’re definitely not blocked. I recently put a branch-protection rule on dev so that all direct pushes need to come in as pull requests instead. Nothing personal at all, this helps us:
- keep the CI green,
- have a short review chat before code lands, and
- avoid accidental conflicts when several of us work in parallel.

I have fixed the compilation already but not added yet the physical conversion function. As it depends on the image, I've added a `TBGRAImageUnitConverter` class that proposes all conversions taking into account the resolution and the font of the image and you can call Resample with any CSS unit. Hopefully that can work with your project.

It could make sense to have as well a function that does just physical CSS units, something very straightforward, without resolution. It would convert for example between mm and inches but not convert between pixels and physical units.

For the future, here is how to proceed to make changes:
- Push your changes to a branch in your fork (e.g. fix/resample-units).
- Open a pull request against dev.
- We can discuss any tweaks right in the PR and merge once everyone’s happy.

If you hit any hiccups with permissions or the PR workflow, just let me know and we’ll sort it out. Thanks for your valuable contributions! 😊

Cheers

**Comment by maxm74** [comment]
In the end it is a function that only converts the measurement from inches to cm, I can work around it by converting the dpi.

As for the compilation problem, it is not solved. just add this to the uses of BGRAUnits

uses
  SysUtils, BGRABitmapTypes
  {$IF FPC_FULLVERSION>30202}
  , FpImage
  {$ENDIF}
  ;

**Comment by circular17** [comment]
Oh I understand. `TResolutionUnit` needs to be imported in BGRABitmapTypes so that it is always available.

I suppose that changing in _geometrytypes.inc_ line 212
```pascal
{$IF FPC_FULLVERSION<30203}
  {* Unit used to specify the resolution of a bitmap }
  TResolutionUnit = (
    {** No unit used, only aspect ratio specified }
    ruNone,
    {** Pixels per inch (DPI) }
    ruPixelsPerInch,
    {** Pixels per centimeters }
    ruPixelsPerCentimeter);
{$ENDIF}  
```
to
```pascal
{$IF FPC_FULLVERSION<30203}
  {* Unit used to specify the resolution of a bitmap }
  TResolutionUnit = (
    {** No unit used, only aspect ratio specified }
    ruNone,
    {** Pixels per inch (DPI) }
    ruPixelsPerInch,
    {** Pixels per centimeters }
    ruPixelsPerCentimeter);
{$ELSE}
   TResolutionUnit = FPImage.TResolutionUnit;
{$ENDIF}  
```
could solve the compilation error. Does it work for you?

**Comment by maxm74** [comment]
is better because TBGRABitmap  use it

**Comment by circular17** [comment]
Ok, let's go with that then (#285).

**Comment by circular17** [comment]
Ok so with latest change, I think it will fix the ru* missing error.

**Comment by paweld** [comment]
now it's OK.
@circular17 Thank you

**Comment by circular17** [comment]
Great.

Thank you all for your help. We solved it. Now I'm releasing a new version of BGRABitmap with this fix.
